---
- name: Deploy a jar file
  hosts: docker
  remote_user: tarun
  tasks:
    - name: Copy jar file to home directory
      copy:
        src: ./target/calculator-0.0.1-SNAPSHOT-jar-with-dependencies.jar
        dest: ~/

- name: Deploy a jar file
  hosts: ubuntu18
  remote_user: user
  tasks:
    - name: Copy jar file to home directory
      copy:
        src: ./target/calculator-0.0.1-SNAPSHOT-jar-with-dependencies.jar
        dest: ~/
